// This script builds the airportTimezones.json file.
// Builds by adding southwest airports list + airport timezone data

var airportTimezone = require("airport-timezone");
const fs = require("fs");

// list of southwest airports
let data = {
  airports: [
    { city: "Albany, NY", code: "ALB" },
    { city: "Albuquerque, NM", code: "ABQ" },
    { city: "Amarillo, TX", code: "AMA" },
    { city: "Aruba, Aruba", code: "AUA" },
    { city: "Atlanta, GA", code: "ATL" },
    { city: "Austin, TX", code: "AUS" },
    { city: "Baltimore/Washington, MD", code: "BWI" },
    { city: "Belize City, Belize", code: "BZE" },
    {
      city: "Bellingham (approx. 50mi from Vancouver, BC), WA",
      code: "BLI",
    },
    { city: "Birmingham, AL", code: "BHM" },
    { city: "Boise, ID", code: "BOI" },
    { city: "Boston (Logan), MA", code: "BOS" },
    { city: "Hartford, CT", code: "BDL" },
    { city: "Manchester, NH", code: "MHT" },
    { city: "Providence, RI", code: "PVD" },
    { city: "Bozeman/Yellowstone, MT", code: "BZN" },
    { city: "Buffalo/Niagara, NY", code: "BUF" },
    { city: "Burbank, CA", code: "BUR" },
    { city: "Cancun, Mexico", code: "CUN" },
    { city: "Cozumel, Quintana Roo", code: "CZM" },
    { city: "Grand Cayman, Cayman Islands", code: "GCM" },
    { city: "Havana, Cuba", code: "HAV" },
    { city: "Montego Bay, Jamaica", code: "MBJ" },
    { city: "Nassau, Bahamas", code: "NAS" },
    { city: "Providenciales, Turks and Caicos", code: "PLS" },
    { city: "Punta Cana, DO", code: "PUJ" },
    { city: "San Juan, PR", code: "SJU" },
    { city: "Liberia (Guanacaste), Costa Rica", code: "LIR" },
    { city: "San Jose, Costa Rica", code: "SJO" },
    { city: "Charleston, SC", code: "CHS" },
    { city: "Charlotte, NC", code: "CLT" },
    { city: "Chicago (Midway), IL", code: "MDW" },
    { city: "Chicago (O’Hare-Terminal 5), IL", code: "ORD" },
    { city: "Cincinnati, OH", code: "CVG" },
    { city: "Cleveland, OH", code: "CLE" },
    { city: "Colorado Springs, CO", code: "COS" },
    { city: "Columbus, OH", code: "CMH" },
    { city: "Corpus Christi, TX", code: "CRP" },
    { city: "Dallas (Love Field), TX", code: "DAL" },
    { city: "Denver, CO", code: "DEN" },
    { city: "Des Moines, IA", code: "DSM" },
    { city: "Destin/Fort Walton Beach, FL", code: "VPS" },
    { city: "Detroit, MI", code: "DTW" },
    { city: "El Paso, TX", code: "ELP" },
    { city: "Eugene, OR", code: "EUG" },
    { city: "Fort Lauderdale, FL", code: "FLL" },
    { city: "Fort Myers, FL", code: "RSW" },
    { city: "Fresno, CA", code: "FAT" },
    { city: "Grand Rapids, MI", code: "GRR" },
    { city: "Greenville/Spartanburg, SC", code: "GSP" },
    { city: "Harlingen, TX", code: "HRL" },
    { city: "Hilo (Hawaii Island), HI", code: "ITO" },
    { city: "Honolulu (Oahu), HI", code: "HNL" },
    { city: "Kahului (Maui), HI", code: "OGG" },
    { city: "Kona (Hawaii Island), HI", code: "KOA" },
    { city: "Lihue (Kauai), HI", code: "LIH" },
    { city: "Houston (Bush-Intercontl), TX", code: "IAH" },
    { city: "Houston (Hobby), TX", code: "HOU" },
    { city: "Indianapolis, IN", code: "IND" },
    { city: "Jackson, MS", code: "JAN" },
    { city: "Jacksonville, FL", code: "JAX" },
    { city: "Kansas City, MO", code: "MCI" },
    { city: "Las Vegas, NV", code: "LAS" },
    { city: "Little Rock, AR", code: "LIT" },
    { city: "Long Beach, CA", code: "LGB" },
    { city: "Long Island/Islip, NY", code: "ISP" },
    { city: "Los Angeles, CA", code: "LAX" },
    { city: "Ontario/LA, CA", code: "ONT" },
    { city: "Orange County/Santa Ana, CA", code: "SNA" },
    { city: "Los Cabos, MX", code: "SJD" },
    { city: "Louisville, KY", code: "SDF" },
    { city: "Lubbock, TX", code: "LBB" },
    { city: "Memphis, TN", code: "MEM" },
    { city: "Miami, FL", code: "MIA" },
    { city: "West Palm Beach, FL", code: "PBI" },
    { city: "Midland/Odessa, TX", code: "MAF" },
    { city: "Milwaukee, WI", code: "MKE" },
    { city: "Minneapolis/St. Paul (Terminal 2), MN", code: "MSP" },
    { city: "Montrose (Telluride/Crested Butte), CO", code: "MTJ" },
    { city: "Myrtle Beach, SC", code: "MYR" },
    { city: "Nashville, TN", code: "BNA" },
    { city: "New Orleans, LA", code: "MSY" },
    { city: "New York (LaGuardia), NY", code: "LGA" },
    { city: "Norfolk, VA", code: "ORF" },
    { city: "Panama City Beach, FL", code: "ECP" },
    { city: "Pensacola, FL", code: "PNS" },
    { city: "Oakland, CA", code: "OAK" },
    { city: "Oklahoma City, OK", code: "OKC" },
    { city: "Omaha, NE", code: "OMA" },
    { city: "Orlando, FL", code: "MCO" },
    { city: "Palm Springs, CA", code: "PSP" },
    { city: "Philadelphia, PA", code: "PHL" },
    { city: "Phoenix, AZ", code: "PHX" },
    { city: "Pittsburgh, PA", code: "PIT" },
    { city: "Portland, ME", code: "PWM" },
    { city: "Portland, OR", code: "PDX" },
    { city: "Puerto Vallarta, MX", code: "PVR" },
    { city: "Raleigh/Durham, NC", code: "RDU" },
    { city: "Reno/Tahoe, NV", code: "RNO" },
    { city: "Richmond, VA", code: "RIC" },
    { city: "Rochester, NY", code: "ROC" },
    { city: "Sacramento, CA", code: "SMF" },
    { city: "Salt Lake City, UT", code: "SLC" },
    { city: "San Antonio, TX", code: "SAT" },
    { city: "San Diego, CA", code: "SAN" },
    { city: "San Francisco, CA", code: "SFO" },
    { city: "San Jose, CA", code: "SJC" },
    { city: "Santa Barbara, CA", code: "SBA" },
    { city: "Sarasota/Bradenton, FL", code: "SRQ" },
    { city: "Savannah/Hilton Head, GA", code: "SAV" },
    { city: "Seattle/Tacoma, WA", code: "SEA" },
    { city: "Spokane, WA", code: "GEG" },
    { city: "St. Louis, MO", code: "STL" },
    { city: "Steamboat Springs (Hayden), CO", code: "HDN" },
    { city: "Syracuse, NY", code: "SYR" },
    { city: "Tampa, FL", code: "TPA" },
    { city: "Tucson, AZ", code: "TUS" },
    { city: "Tulsa, OK", code: "TUL" },
    { city: "Washington (Dulles), DC", code: "IAD" },
    { city: "Washington (Reagan National), DC", code: "DCA" },
    { city: "Wichita, KS", code: "ICT" },
  ],
};

// combine the airport lists into a single list with timezone data
let airportTimezones = [];
data.airports.forEach((airport) => {
  // get timezone data and add it to the new list
  var TZdata = airportTimezone.filter(function (_airport) {
    return airport.code === _airport.code;
  })[0];
  airportTimezones = [...airportTimezones, { ...TZdata, ...airport }];
});

// save data as json
let dataString = JSON.stringify(airportTimezones);
fs.writeFileSync("airportTimezones.json", dataString);
